Repository Bamdoliro/marururu, pull requests merged in 2023-07, with the labels that each got.

#112 폴더 컨벤션 변경
  apps/user/src/apis/instance/instance.ts
  apps/user/src/apis/storage/storage.ts
  apps/user/src/apis/token/refresh.ts
  apps/user/src/apis/token/token.ts
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/login/login.hook.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/notice/[detail]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hook.ts
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Icons/Faq.tsx
  apps/user/src/components/faq/CategoryFilter/Category.tsx
  apps/user/src/components/faq/CategoryFilter/CategoryFilter.tsx
  apps/user/src/components/faq/FaqItem/FaqItem.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/components/main/Dday/Dday.hook.ts
  apps/user/src/components/main/Dday/Dday.tsx
  apps/user/src/components/main/Faq/Faq.tsx
  apps/user/src/components/main/Faq/FaqItem.tsx
  apps/user/src/components/main/Notice/Notice.tsx
  apps/user/src/components/main/Notice/NoticeItem.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
  apps/user/src/components/main/Schedule/ScheduleItem.tsx
  apps/user/src/components/notice/NoticeHeader/NoticeHeader.tsx
  apps/user/src/components/notice/NoticeItem/NoticeItem.tsx
  apps/user/src/components/signup/Terms/Terms.hook.ts
  apps/user/src/components/signup/Terms/Terms.tsx
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/FaqLayout.tsx
  apps/user/src/layouts/FormLayout.tsx
  apps/user/src/layouts/MainLayout.tsx
  apps/user/src/layouts/NoticeLayout.tsx
  apps/user/src/services/QueryClientProvider.tsx
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  packages/maru-ui/Icons/Icon.type.ts
  packages/maru-ui/Icons/InvisibleEye.tsx
  packages/maru-ui/Icons/Search.tsx
  packages/maru-ui/Icons/VisibleEye.tsx
  packages/maru-ui/components/Button/Button.style.ts
  packages/maru-ui/components/Button/Button.tsx
  packages/maru-ui/components/Button/Button.type.ts
  packages/maru-ui/components/Button/type.ts
  packages/maru-ui/components/Dropdown/Dropdown.tsx
  packages/maru-ui/components/Flex/Column.tsx
  packages/maru-ui/components/Flex/Flex.type.ts
  packages/maru-ui/components/Flex/Row.tsx
  packages/maru-ui/components/Input/Button.tsx
  packages/maru-ui/components/Input/Button.type.ts
  packages/maru-ui/components/Input/ButtonInput.tsx
  packages/maru-ui/components/Input/PreviewInput.tsx
  packages/maru-ui/components/Input/SearchInput.tsx
  packages/maru-ui/components/Input/TimerInput.tsx
  packages/maru-ui/components/Link/Link.tsx
  packages/maru-ui/index.ts
Labels: 🔨 Refactor

#119 TimeLimitInput 리팩토링
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hook.ts
  apps/user/src/constants/submitTime.ts
  packages/maru-hooks/index.ts
  packages/maru-hooks/src/useTimer.ts
  packages/maru-ui/components/Input/ButtonInput.tsx
  packages/maru-ui/components/Input/Input.tsx
  packages/maru-ui/components/Input/Input.type.ts
  packages/maru-ui/components/Input/PreviewInput.tsx
  packages/maru-ui/components/Input/SearchInput.tsx
  packages/maru-ui/components/Input/TimeLimitInput.tsx
  packages/maru-ui/hooks/useTimer.ts
  packages/maru-ui/index.ts
  packages/maru-ui/package.json
  packages/maru-utils/functions/formatTime.ts
  packages/maru-utils/index.ts
Labels: 🔨 Refactor

#129 dayjs에 isBetween과 utc 기능에 나타난 에러 수정
  apps/user/src/app/layout.tsx
  apps/user/src/components/main/Dday/Dday.hooks.ts
Labels: 🐞 Bug

#132 디자인에 맞게 footer 수정
  apps/user/src/components/common/Footer/Footer.tsx
Labels: 🔨 Refactor

#134 hook을 hooks로 바꾸었습니다
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/hooks/useFormPage.ts
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/BaseLayout.tsx
Labels: 🔨 Refactor

#136 디펜던시, 데브디펜던시 분리
  .yarn/cache/@emotion-is-prop-valid-npm-1.2.1-794afe6a94-8f42dc573a.zip
  .yarn/cache/@emotion-memoize-npm-0.8.1-9b1e35ff15-a19cc01a29.zip
  .yarn/cache/@types-stylis-npm-4.2.0-5addc9ed60-02a47584ac.zip
  .yarn/cache/styled-components-npm-6.0.0-rc.2-4007-2deced225d-b63dc76343.zip
  .yarn/cache/styled-components-npm-6.0.3-7d0bb0ee44-e02e6a38a7.zip
  .yarn/cache/stylis-npm-4.2.0-6b07f11c99-0eb6cc1b86.zip
  .yarn/cache/stylis-npm-4.3.0-cec5472bed-6120de3f03.zip
  apps/user/package.json
  packages/maru-hooks/package.json
  packages/maru-theme/package.json
  packages/maru-ui/package.json
  packages/maru-utils/package.json
  yarn.lock
Labels: 🔨 Refactor

#137 components/ 폴더에 index.ts 파일 추가했습니다.
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/login/page.tsx
  apps/user/src/app/notice/[detail]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Header/Profile.tsx
  apps/user/src/components/common/Icons/index.ts
  apps/user/src/components/common/index.ts
  apps/user/src/components/faq/FaqItem/FaqItem.tsx
  apps/user/src/components/faq/index.ts
  apps/user/src/components/form/index.ts
  apps/user/src/components/main/Faq/Faq.tsx
  apps/user/src/components/main/Faq/FaqItem.tsx
  apps/user/src/components/main/Notice/Notice.tsx
  apps/user/src/components/main/index.ts
  apps/user/src/components/notice/NoticeItem/NoticeItem.tsx
  apps/user/src/components/notice/index.ts
  apps/user/src/components/signup/Terms/Terms.tsx
  apps/user/src/components/signup/index.ts
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/FormLayout.tsx
Labels: ✨ Feature, 🔨 Refactor

#141 constants object 형식으로 변경
  apps/user/src/apis/instance/index.ts
  apps/user/src/apis/token/index.ts
  apps/user/src/apis/token/refresh.ts
  apps/user/src/apis/token/token.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/notice/[detail]/page.tsx
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/main/Faq/Faq.tsx
  apps/user/src/components/main/Faq/FaqItem.tsx
  apps/user/src/components/main/Notice/Notice.tsx
  apps/user/src/components/main/Notice/NoticeItem.tsx
  apps/user/src/components/notice/NoticeItem/NoticeItem.tsx
  apps/user/src/constants/key.ts
  apps/user/src/constants/routes.ts
  apps/user/src/constants/token.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/faq/queries.ts
  apps/user/src/services/main/queries.ts
  apps/user/src/services/notice/queries.ts
  packages/maru-ui/components/Dropdown/Dropdown.tsx
Labels: 🔨 Refactor

#148 원서접수 지원자 정보 개발
  apps/user/src/app/form/page.tsx
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.hooks.ts
  apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
  apps/user/src/components/form/지원자정보/지원자정보.tsx
  apps/user/src/components/main/Dday/Dday.hooks.ts
  apps/user/src/services/form/.gitkeep
  apps/user/src/services/form/지원자정보/api.ts
  apps/user/src/services/form/지원자정보/mutations.ts
  packages/maru-hooks/package.json
  packages/maru-hooks/src/useInterval.ts
  packages/maru-ui/components/Dropdown/Dropdown.tsx
  packages/maru-ui/components/Flex/Flex.type.ts
  packages/maru-ui/components/Radio/Radio.tsx
  packages/maru-ui/index.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#150 원서접수 보호자 정보 개발
  apps/user/package.json
  apps/user/src/app/form/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/components/form/보호자정보/FindAddressModal/FindAddressModal.tsx
  apps/user/src/components/form/보호자정보/보호자정보.tsx
  package.json
  packages/maru-hooks/index.ts
  packages/maru-hooks/package.json
  packages/maru-hooks/src/useOutsideClick.ts
  packages/maru-ui/components/Input/ButtonInput.tsx
  packages/maru-ui/components/Input/Input.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#147 원서접수 출신학교 및 학력 개발
  apps/user/src/app/form/page.tsx
  apps/user/src/components/form/Modal/SchoolSearchModal.hooks.ts
  apps/user/src/components/form/Modal/SchoolSearchModal.tsx
  apps/user/src/components/form/지원자정보/지원자정보.tsx
  apps/user/src/components/form/출신학교및학력/index.tsx
  apps/user/src/constants/key.ts
  apps/user/src/services/form/출신학교및학력/api.ts
  apps/user/src/services/form/출신학교및학력/queries.ts
  apps/user/tsconfig.json
  packages/maru-hooks/src/useModal.ts
  packages/maru-ui/Icons/Check.tsx
  packages/maru-ui/Icons/Close.tsx
  packages/maru-ui/components/Input/ButtonInput.tsx
  packages/maru-ui/components/Radio/Radio.tsx
  packages/maru-ui/components/Radio/RadioGroup.tsx
  packages/maru-ui/index.ts
Labels: ✨ Feature

#154 funnel 대체제 세팅
  apps/user/package.json
  apps/user/src/apis/instance/instance.ts
  apps/user/src/apis/storage/storage.ts
  apps/user/src/apis/token/refresh.ts
  apps/user/src/apis/token/token.ts
  apps/user/src/app/form/page.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/components/Provider.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/form/FormController/FormController.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/components/form/보호자정보/보호자정보.tsx
  apps/user/src/components/form/지원자정보/지원자정보.tsx
  apps/user/src/components/form/출신학교및학력/SchoolSearchModal/SchoolSearchModal.hooks.ts
  apps/user/src/components/form/출신학교및학력/SchoolSearchModal/SchoolSearchModal.tsx
  apps/user/src/components/form/출신학교및학력/index.tsx
  apps/user/src/components/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/hooks/index.ts
  apps/user/src/hooks/useForm.ts
  apps/user/src/hooks/useFormPage.ts
  apps/user/src/layouts/FormLayout.tsx
  apps/user/src/services/QueryClientProvider.tsx
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/form/지원자정보/api.ts
  apps/user/src/store/form/form.ts
  packages/maru-ui/components/Button/Button.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#153 원서접수 전형 선택 페이지 개발
  apps/user/src/app/form/page.tsx
  apps/user/src/components/form/전형선택/전형선택.hooks.ts
  apps/user/src/components/form/전형선택/전형선택.tsx
  apps/user/src/components/form/출신학교및학력/FindSchoolModal/FindSchoolModal.hooks.ts
  apps/user/src/components/form/출신학교및학력/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/layouts/FormLayout.tsx
Labels: ✨ Feature

#156 원서접수 성적입력 페이지 프레임 개발
  apps/user/src/app/form/page.tsx
  apps/user/src/components/form/성적입력/성적입력.tsx
Labels: ✨ Feature

#164 원서접수 자기소개서 개발
  apps/user/src/app/form/page.tsx
  apps/user/src/components/form/FormController/FormController.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/components/form/보호자정보/보호자정보.tsx
  apps/user/src/components/form/자기소개서/자기소개서.tsx
  apps/user/src/components/form/전형선택/전형선택.tsx
  apps/user/src/components/form/지원자정보/지원자정보.tsx
  apps/user/src/components/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/components/notice/NoticeHeader/NoticeHeader.tsx
  apps/user/src/layouts/FormLayout.tsx
  packages/maru-ui/components/Dropdown/Dropdown.tsx
  packages/maru-ui/components/Input/ButtonInput.tsx
  packages/maru-ui/components/Input/Input.tsx
  packages/maru-ui/components/Input/PreviewInput.tsx
  packages/maru-ui/components/Input/TimeLimitInput.tsx
  packages/maru-ui/components/Textarea/Textarea.tsx
  packages/maru-ui/index.ts
Labels: ✨ Feature

#162 비즈니스 로직 분리 리팩토링
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/faq/Category/Category.tsx
  apps/user/src/components/faq/CategoryFilter/CategoryFilter.tsx
  apps/user/src/components/form/보호자정보/FindAddressModal/FindAddressModal.tsx
  apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.hooks.ts
  apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculatorItem/GradeCalculatorItem.hooks.ts
  apps/user/src/components/form/성적입력/GradeCalculator/NewGradeCalculatorItem/NewGradeCalculatorItem.hooks.ts
  apps/user/src/components/form/성적입력/GradeCalculatorHeader/GradeCalculatorHeader.tsx
  apps/user/src/components/form/성적입력/GradeCalculatorItem/GradeCalculatorItem.tsx
  apps/user/src/components/form/성적입력/NewGradeCalculatorItem/NewGradeCalculatorItem.tsx
  apps/user/src/components/form/전형선택/전형선택.hooks.ts
  apps/user/src/components/form/전형선택/전형선택.tsx
  apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.hooks.ts
  apps/user/src/components/form/출신학교및학력/FindSchoolModal/FindSchoolModal.hooks.ts
  apps/user/src/components/form/출신학교및학력/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/main/Faq/Faq.tsx
  apps/user/src/components/main/FaqItem/FaqItem.tsx
  apps/user/src/components/main/Notice/Notice.tsx
  apps/user/src/components/main/NoticeItem/NoticeItem.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
  apps/user/src/components/main/ScheduleItem/ScheduleItem.tsx
  apps/user/src/components/signup/Terms/Terms.hook.ts
  apps/user/src/components/signup/Terms/Terms.tsx
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/form/출신학교및학력/queries.ts
  apps/user/src/types/form/index.ts
  packages/maru-hooks/src/useInput.ts
Labels: 🔨 Refactor

#166 학교 검색 API를 나이스에서 밤돌이로 개발 서버 API로 변경했습니다
  apps/user/src/components/form/출신학교및학력/FindSchoolModal/FindSchoolModal.hooks.ts
  apps/user/src/components/form/출신학교및학력/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/services/form/출신학교및학력/api.ts
  apps/user/src/services/form/출신학교및학력/queries.ts
  packages/maru-ui/components/Radio/RadioGroup.tsx
Labels: ✨ Feature

#168 전형 선택 데이터 핸들링 및 리팩토링
  apps/user/src/app/form/index.ts
  apps/user/src/app/form/page.tsx
  apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/성적입력/성적입력.tsx
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.tsx
  apps/user/src/app/form/전형선택/전형선택.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/components/form/FindAddressModal/FindAddressModal.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.hooks.ts
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/FormController/FormController.tsx
  apps/user/src/components/form/ProfileUpload/ProfileUpload.hooks.ts
  apps/user/src/components/form/ProfileUpload/ProfileUpload.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/components/form/Tables/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Tables/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/Tables/GradeCalculator/GradeCalculator.hooks.ts
  apps/user/src/components/form/Tables/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Tables/GradeCalculatorHeader/GradeCalculatorHeader.tsx
  apps/user/src/components/form/Tables/GradeCalculatorItem/GradeCalculatorItem.tsx
  apps/user/src/components/form/Tables/GradePreview/GradePreview.tsx
  apps/user/src/components/form/Tables/NewGradeCalculatorItem/NewGradeCalculatorItem.tsx
  apps/user/src/components/form/Tables/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/Tables/index.ts
  apps/user/src/components/form/apps/전형선택/전형선택.hooks.ts
  apps/user/src/components/form/index.ts
  packages/maru-hooks/index.ts
  packages/maru-hooks/src/useDebounceInput.ts
  packages/maru-ui/index.ts
Labels: ✨ Feature

#169 컴포넌트 비즈니스 로직 분리 취소 및 api 문서에 맞게 코드를 변경
  apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.tsx
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
  apps/user/src/app/notice/[detail]/page.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculatorHeader/GradeCalculatorHeader.tsx
  apps/user/src/components/form/Calculators/GradeCalculatorItem/GradeCalculatorItem.tsx
  apps/user/src/components/form/Calculators/GradePreview/GradePreview.tsx
  apps/user/src/components/form/Calculators/NewGradeCalculatorItem/NewGradeCalculatorItem.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/Calculators/index.ts
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.hooks.ts
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/ProfileUpload/ProfileUpload.hooks.ts
  apps/user/src/components/form/ProfileUpload/ProfileUpload.tsx
  apps/user/src/components/form/Tables/GradeCalculator/GradeCalculator.hooks.ts
  apps/user/src/components/form/index.ts
  apps/user/src/components/notice/NoticeHeader/NoticeHeader.tsx
  apps/user/src/components/notice/index.ts
  apps/user/src/constants/form.ts
  apps/user/src/services/form/지원자정보/mutations.ts
  apps/user/src/types/form/index.ts
  apps/user/src/utils/formatDate.ts
  packages/maru-ui/components/Dropdown/Dropdown.tsx
Labels: 🔨 Refactor

#171 스케쥴 컴포넌트 바뀐 디자인 수정
  apps/user/src/app/page.tsx
  apps/user/src/components/main/Dday/Dday.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
Labels: ✨ Feature

#174 원서접수 성적입력 테이블 데이터 핸들링
  apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  packages/maru-ui/components/CheckBox/CheckBox.tsx
  packages/maru-ui/components/Input/NumberInput.tsx
  packages/maru-ui/components/Radio/Radio.tsx
  packages/maru-ui/components/Radio/RadioGroup.tsx
  packages/maru-ui/index.ts
Labels: ✨ Feature
