Repository Bamdoliro/marururu, pull requests merged in 2023-10, with the labels that each got.

#442 머리부터발끝까지핫픽스
  apps/admin/src/components/form/FormDetailContent/성적/교과성적/교과성적.tsx
  apps/user/src/components/common/Wrappers/AuthWrapper/AuthWrapper.tsx
  apps/user/src/components/form/Calculators/ScoreCalculator/GradeCalculator/GradeCalculator.tsx
Labels: 🐞 Bug

#444 레이아웃 쉬프트 현상 수정
  apps/user/next.config.js
  apps/user/src/app/layout.tsx
  apps/user/src/lib/registry.tsx
Labels: 🐞 Bug

#449 feat(ui): Text 컴포넌트 tag prop 추가
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/components/result/FinalResultTable/FinalResultTable.tsx
  apps/user/src/components/result/FirstResultTable/FirstResultTable.tsx
  apps/user/src/components/result/ResultMain/ResultMain.tsx
  apps/user/src/components/result/ResultTableFooter/ResultTableFooter.tsx
  apps/user/src/components/result/ResultTableItem/ResultTableItem.tsx
  apps/user/src/hooks/useGradeCaculation.ts
  packages/maru-theme/src/global.ts
  packages/maru-ui/src/Text/Text.tsx
Labels: ✨ Feature

#376 reafctor(user): StudentSubject Omit으로 변형
  apps/user/src/hooks/useGradeCaculation.ts
  apps/user/src/types/form/client.ts
Labels: 🔨 Refactor

#453 feat: lighthouse ci 추가
  .github/workflows/lighthouse-ci.yml
  .lighthouserc.js
  package.json
  pnpm-lock.yaml
Labels: ✨ Feature

#456 feat(user): suspensive 적용
  .lighthouserc.js
  apps/user/package.json
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/components/Provider.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/main/FaqBox/FaqBox.tsx
  apps/user/src/components/main/NoticeBox/NoticeBox.tsx
  apps/user/src/services/faq/queries.ts
  apps/user/src/services/form/queries.ts
  apps/user/src/services/notice/queries.ts
  pnpm-lock.yaml
  turbo.json
Labels: 🔨 Refactor
