Repository Bamdoliro/marururu, pull requests merged in 2023-08, with the labels that each got.

#173 원서접수 완료화면 개발
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/form/complete/page.tsx
  apps/user/src/app/login/page.tsx
  apps/user/src/app/notice/[detail]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/form/CompleteAlaram/CompleteAlaram.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/BaseLayout.tsx
  apps/user/src/layouts/index.ts
  packages/maru-icon/index.ts
  packages/maru-icon/src/IconCancelCircle.tsx
  packages/maru-icon/src/IconCheckCircle.tsx
  packages/maru-ui/Icons/Icon.type.ts
  packages/maru-ui/src/Flex/Column.tsx
  packages/maru-ui/src/Flex/Flex.type.ts
  packages/maru-ui/src/Flex/Row.tsx
Labels: ✨ Feature

#183 공지사항 API 연결
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/components/main/Notice/Notice.tsx
  apps/user/src/components/notice/NoticeItem/NoticeItem.tsx
  apps/user/src/constants/key.ts
  apps/user/src/services/main/api.ts
  apps/user/src/services/main/queries.ts
  apps/user/src/services/notice/api.ts
  apps/user/src/services/notice/queries.ts
  packages/maru-icon/src/IconArrowLeft.tsx
  packages/maru-utils/functions/formatCreatedAt.ts
  packages/maru-utils/index.ts
Labels: ✨ Feature

#181 리프래쉬 토큰 재발급 오류 수정
  apps/user/src/apis/instance/instance.ts
  apps/user/src/apis/token/refresh.ts
  apps/user/src/components/main/Dday/Dday.tsx
Labels: 🔨 Refactor

#179 원서접수 초안제출 API 연결
  apps/user/package.json
  apps/user/src/app/form/form.state.ts
  apps/user/src/app/form/index.ts
  apps/user/src/app/form/page.tsx
  apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
  apps/user/src/app/form/보호자정보/보호자정보.state.ts
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/성적입력/성적입력.hooks.ts
  apps/user/src/app/form/성적입력/성적입력.state.ts
  apps/user/src/app/form/성적입력/성적입력.tsx
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.tsx
  apps/user/src/app/form/전형선택/전형선택.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.state.ts
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.state.ts
  apps/user/src/app/form/지원자정보/지원자정보.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
  apps/user/src/app/form/출신학교및학력/출신학교및학력.state.ts
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/faq/CategoryFilter/Category/Category.tsx
  apps/user/src/components/faq/CategoryFilter/CategoryFilter.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/FindAddressModal/FindAddressModal.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/ProfileUpload/ProfileUpload.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/hooks/index.ts
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/hooks/useFormState.ts
  apps/user/src/hooks/useFormStep.ts
  apps/user/src/services/auth/api.ts
  apps/user/src/services/form/.gitkeep
  apps/user/src/services/form/api.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/services/form/지원자정보/mutations.ts
  apps/user/src/services/form/출신학교및학력/api.ts
  apps/user/src/services/form/출신학교및학력/queries.ts
  apps/user/src/services/main/queries.ts
  apps/user/src/store/form/index.ts
  apps/user/src/types/form/index.ts
  packages/maru-ui/src/Button/Button.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#186 리디자인 된 완료화면 개발
  apps/user/src/app/form/complete/page.tsx
  apps/user/src/app/login/page.tsx
  apps/user/src/components/form/CheckFormCompleteItem/CheckFormCompleteItem.tsx
  apps/user/src/components/form/CompleteAlaram/CompleteAlaram.tsx
  apps/user/src/components/form/index.ts
Labels: ✨ Feature

#193 자주묻는질문 API 연결
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/components/faq/FaqList/FaqItem/FaqItem.tsx
  apps/user/src/components/faq/FaqList/FaqList.tsx
  apps/user/src/components/faq/index.ts
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
  apps/user/src/components/main/Faq/MainFaq.tsx
  apps/user/src/components/main/Faq/MainFaqList/MainFaqItem/MainFaqItem.tsx
  apps/user/src/components/main/Faq/MainFaqList/MainFaqList.tsx
  apps/user/src/components/main/Notice/MainNotice.tsx
  apps/user/src/components/main/Notice/MainNoticeList/MainNoticeItem/MainNoticeItem.tsx
  apps/user/src/components/main/Notice/MainNoticeList/MainNoticeList.tsx
  apps/user/src/components/main/index.ts
  apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.tsx
  apps/user/src/components/notice/NoticeList/NoticeItem/NoticeItem.tsx
  apps/user/src/components/notice/NoticeList/NoticeList.tsx
  apps/user/src/components/notice/index.ts
  apps/user/src/constants/key.ts
  apps/user/src/services/faq/api.ts
  apps/user/src/services/faq/queries.ts
  apps/user/src/services/form/출신학교및학력/api.ts
  apps/user/src/services/form/출신학교및학력/queries.ts
  apps/user/src/services/main/api.ts
  apps/user/src/services/main/queries.ts
  apps/user/src/services/notice/api.ts
  apps/user/src/services/notice/queries.ts
  apps/user/src/types/faq/index.ts
  apps/user/src/types/form/index.ts
  apps/user/src/types/notice/index.ts
Labels: ✨ Feature

#189 원서접수 완료 화면 기능 개발
  apps/user/src/app/form/page.tsx
  apps/user/src/app/form/완료/완료.hooks.ts
  apps/user/src/app/form/완료/완료.tsx
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/components/form/CheckFormCompleteItem/CheckFormCompleteItem.tsx
  apps/user/src/components/form/CompleteAlaram/CompleteAlaram.tsx
  apps/user/src/types/form/index.ts
  apps/user/src/utils/formatDate.ts
  packages/maru-icon/index.ts
  packages/maru-icon/src/IconError.tsx
Labels: ✨ Feature

#191 @maru/ui 버튼 분리
  apps/user/src/app/form/성적입력/성적입력.tsx
  apps/user/src/components/common/Header/Header.tsx
  packages/maru-ui/index.ts
  packages/maru-ui/src/Button/Button.style.ts
  packages/maru-ui/src/Button/Button.type.ts
  packages/maru-ui/src/Button/UnderLineButton.tsx
  packages/maru-ui/src/Link/Link.tsx
Labels: 🔨 Refactor

#199 전체적인 리팩토링
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/form/form.state.ts
  apps/user/src/app/form/보호자정보/보호자정보.state.ts
  apps/user/src/app/form/성적입력/성적입력.state.ts
  apps/user/src/app/form/지원자정보/지원자정보.state.ts
  apps/user/src/app/form/출신학교및학력/출신학교및학력.state.ts
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/faq/FaqList/FaqList.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculatorItem/GradeCalculatorItem.tsx
  apps/user/src/components/form/Calculators/NewGradeCalculatorItem/NewGradeCalculatorItem.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/FindAddressModal/FindAddressModal.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
  apps/user/src/components/form/FormController/FormController.tsx
  apps/user/src/components/form/ProfileUpload/ProfileUpload.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/components/main/Faq/MainFaq.tsx
  apps/user/src/components/main/Faq/MainFaqList/MainFaqList.tsx
  apps/user/src/components/main/Notice/MainNotice.tsx
  apps/user/src/components/main/Notice/MainNoticeList/MainNoticeList.tsx
  apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.tsx
  apps/user/src/components/notice/NoticeList/NoticeList.tsx
  apps/user/src/components/notice/index.ts
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/faq/api.ts
  apps/user/src/services/faq/queries.ts
  apps/user/src/services/form/api.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/services/form/queries.ts
  apps/user/src/services/notice/api.ts
  apps/user/src/services/notice/queries.ts
  apps/user/src/types/auth/remote.ts
  apps/user/src/types/faq/client.ts
  apps/user/src/types/faq/remote.ts
  apps/user/src/types/form/client.ts
  apps/user/src/types/form/remote.ts
  apps/user/src/types/notice/client.ts
  apps/user/src/types/notice/remote.ts
Labels: 🔨 Refactor

#204 디자인 시스템 모달 개발
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/완료/완료.tsx
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/app/not-found.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/Provider.tsx
  apps/user/src/components/form/CheckFormComplete/CheckFormComplete.tsx
  apps/user/src/components/form/FindAddressModal/FindAddressModal.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/hooks/state/useModalState.ts
  apps/user/src/hooks/useModal.ts
  apps/user/src/utils/functions/formatDate.ts
  apps/user/src/utils/functions/formatDay.ts
  apps/user/src/utils/index.ts
  apps/user/src/utils/react/ModalProvider.tsx
  apps/user/tsconfig.json
  packages/maru-hooks/index.ts
  packages/maru-hooks/src/useBoolean.ts
  packages/maru-hooks/src/useModal.ts
  packages/maru-ui/index.ts
  packages/maru-ui/src/Confirm/Confirm.tsx
  packages/maru-ui/src/Dropdown/Dropdown.tsx
  packages/maru-ui/src/Input/ButtonInput.tsx
  packages/maru-ui/src/Modal/Modal.tsx
  packages/maru-ui/src/Radio/Radio.tsx
  packages/maru-ui/src/Radio/RadioGroup.tsx
  packages/maru-ui/src/Table/Table.type.ts
  packages/maru-ui/src/Table/Td.tsx
  packages/maru-ui/src/Table/Th.tsx
Labels: ✨ Feature

#188 원서접수 페이지에 하위 페이지 내 이동 시 이동 전 페이지의 데이터 보이게 수정하기
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.state.ts
  apps/user/src/app/form/자기소개서/자기소개서.tsx
  apps/user/src/app/form/전형선택/전형선택.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.state.ts
  apps/user/src/app/form/지원자정보/지원자정보.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/FormController/FormController.tsx
  apps/user/src/components/form/ProfileUpload/ProfileUpload.tsx
  packages/maru-ui/src/Radio/RadioGroup.tsx
Labels: ✨ Feature

#207 @toss/use-overlay 적용
  apps/user/package.json
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/완료/완료.hooks.ts
  apps/user/src/app/form/완료/완료.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/components/Provider.tsx
  apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
  apps/user/src/components/form/FindAddressModal/FindAddressModal.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/hooks/index.ts
  apps/user/src/hooks/state/useModalState.ts
  apps/user/src/hooks/useModal.ts
  apps/user/src/utils/index.ts
  apps/user/src/utils/react/ModalProvider.tsx
  packages/maru-ui/src/Confirm/Confirm.tsx
  packages/maru-ui/src/Modal/Modal.tsx
  pnpm-lock.yaml
Labels: 🔨 Refactor

#208 원서접수 최종제출 퍼블리싱
  apps/user/src/app/form/page.tsx
  apps/user/src/app/form/초안제출/초안제출.hooks.ts
  apps/user/src/app/form/초안제출/초안제출.tsx
  apps/user/src/app/form/최종제출/최종제출.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculatorHeader/GradeCalculatorHeader.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculatorItem/GradeCalculatorItem.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/NewGradeCalculatorItem/NewGradeCalculatorItem.tsx
  apps/user/src/components/form/Calculators/GradePreview/GradePreview.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/Calculators/index.ts
  apps/user/src/components/form/FinalFormTable/FinalFormTable.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/types/form/client.ts
  packages/maru-ui/src/Table/Table.type.ts
  packages/maru-ui/src/Table/Td.tsx
  packages/maru-ui/src/Table/Th.tsx
Labels: ✨ Feature

#209 원서접수 초안 제출 완료 페이지 퍼블리싱
  apps/user/src/app/form/page.tsx
  apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/app/form/초안제출완료/초안제출완료.tsx
  apps/user/src/components/form/CompleteAlaram/CompleteAlaram.tsx
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/types/form/client.ts
Labels: ✨ Feature

#213 자주 묻는 질문 카테고리 데이터
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/form/성적입력/성적입력.state.ts
  apps/user/src/components/faq/CategoryFilter/CategoryFilter.tsx
  apps/user/src/components/faq/FaqList/FaqList.tsx
  apps/user/src/components/main/Dday/Dday.hooks.ts
  apps/user/src/constants/service/form.ts
  apps/user/src/constants/service/submitTime.ts
Labels: ✨ Feature

#215 원서접수 최종제출완료 개발
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/app/form/초안제출완료/초안제출완료.tsx
  apps/user/src/app/form/최종제출완료/최종제출완료.tsx
  apps/user/src/components/form/CompleteAlaram/CompleteAlaram.tsx
  apps/user/src/services/form/mutations.ts
  apps/user/src/types/form/client.ts
Labels: ✨ Feature

#217 회원가입 이름 추가
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/types/auth/remote.ts
  packages/maru-hooks/index.ts
  packages/maru-hooks/src/useTimer.ts
Labels: ✨ Feature

#218 useUser hook 개발
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/constants/key.ts
  apps/user/src/hooks/state/useUserState.ts
  apps/user/src/hooks/useUser.tsx
  apps/user/src/services/form/queries.ts
  apps/user/src/services/user/api.ts
  apps/user/src/services/user/queries.ts
  apps/user/src/types/user/client.ts
  apps/user/src/types/user/remote.ts
Labels: ✨ Feature

#220 원서접수 원서 초안 다운로드 개발
  apps/user/src/apis/token/token.ts
  apps/user/src/app/form/최종제출/최종제출.hooks.ts
  apps/user/src/app/form/최종제출/최종제출.state.ts
  apps/user/src/constants/token.ts
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/services/form/api.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/services/form/queries.ts
  apps/user/src/types/form/client.ts
Labels: ✨ Feature

#223 token.ts 리팩토링
  apps/user/src/apis/token/token.ts
  apps/user/src/services/form/api.ts
Labels: 🔨 Refactor

#225 #206 브랜치의 충돌 해결
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/form/성적입력/성적입력.tsx
  apps/user/src/app/form/전형선택/전형선택.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.state.ts
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/components/faq/CategoryFilter/CategoryFilter.tsx
  apps/user/src/components/faq/FaqList/FaqList.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Calculators/GradePreview/GradePreview.hooks.ts
  apps/user/src/components/form/Calculators/GradePreview/GradePreview.tsx
  apps/user/src/components/main/Faq/MainFaqList/MainFaqList.tsx
  apps/user/src/components/main/Notice/MainNoticeList/MainNoticeList.tsx
  apps/user/src/components/notice/NoticeList/NoticeList.tsx
  apps/user/src/constants/service/form.ts
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/services/faq/api.ts
  apps/user/src/services/faq/queries.ts
  apps/user/src/types/form/client.ts
  packages/maru-ui/index.ts
  packages/maru-ui/src/RadioGroup/RadioGroup.tsx
Labels: 🐞 Bug

#201 프로필 메뉴 제작하기
  apps/user/src/app/form/지원자정보/지원자정보.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/faq/CategoryFilter/Category/Category.tsx
  apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/constants/token.ts
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/types/form/client.ts
  packages/maru-ui/src/Button/UnderLineButton.tsx
  packages/maru-ui/src/Confirm/Confirm.tsx
  packages/maru-ui/src/Dropdown/Dropdown.tsx
  packages/maru-ui/src/RadioGroup/RadioGroup.tsx
Labels: ✨ Feature

#229 Suspense로 로딩 처리
  apps/user/package.json
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Loader/Loader.tsx
  apps/user/src/components/common/index.ts
  apps/user/src/components/faq/FaqList/FaqList.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
  apps/user/src/components/main/Faq/MainFaq.tsx
  apps/user/src/components/main/Faq/MainFaqList/MainFaqList.tsx
  apps/user/src/components/main/Notice/MainNotice.tsx
  apps/user/src/components/main/Notice/MainNoticeList/MainNoticeList.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
  apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.tsx
  apps/user/src/components/notice/NoticeList/NoticeList.tsx
  apps/user/src/components/notice/index.ts
  apps/user/src/services/QueryClientProvider.tsx
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/faq/queries.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/services/form/queries.ts
  apps/user/src/services/notice/queries.ts
  apps/user/src/services/user/queries.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#230 원서접수 중간저장 개발
  apps/user/src/app/form/form.state.ts
  apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
  apps/user/src/app/form/성적입력/성적입력.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.state.ts
  apps/user/src/app/form/지원자정보/지원자정보.tsx
  apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/app/form/초안제출완료/초안제출완료.tsx
  apps/user/src/app/form/최종제출/최종제출.hooks.ts
  apps/user/src/app/form/최종제출/최종제출.state.ts
  apps/user/src/app/form/최종제출/최종제출.tsx
  apps/user/src/app/form/최종제출완료/최종제출완료.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
  apps/user/src/app/page.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/constants/key.ts
  apps/user/src/services/QueryClientProvider.tsx
  apps/user/src/services/form/api.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/services/form/queries.ts
  apps/user/src/services/user/queries.ts
  apps/user/src/types/form/client.ts
  apps/user/src/types/form/remote.ts
Labels: ✨ Feature

#234 원서 접수 완료 페이지 애니메이션 추가하고 바뀐 디자인 적용했습니다
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/app/login/page.tsx
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/layouts/AppLayout.tsx
  packages/maru-theme/src/font.ts
Labels: ✨ Feature

#235 에러 핸들링
  apps/user/src/components/Provider.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/common/Loader/Loader.tsx
  apps/user/src/hooks/useUser.tsx
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/form/mutations.ts
  packages/maru-utils/functions/axiosErrorTemplate.ts
  packages/maru-utils/index.ts
Labels: ✨ Feature

#239 admin 프로젝트 세팅했습니다
  apps/admin/.eslintrc.json
  apps/admin/.gitignore
  apps/admin/README.md
  apps/admin/next.config.js
  apps/admin/package.json
  apps/admin/public/next.svg
  apps/admin/public/vercel.svg
  apps/admin/src/app/favicon.ico
  apps/admin/src/app/globals.css
  apps/admin/src/app/layout.tsx
  apps/admin/src/app/page.module.css
  apps/admin/src/app/page.tsx
  apps/admin/tsconfig.json
  pnpm-lock.yaml
Labels: ✨ Feature, 🔨 Refactor

#245 유저 스토리북 세팅
  apps/user/.eslintrc.js
  apps/user/.storybook/main.ts
  apps/user/.storybook/preview.ts
  apps/user/package.json
  pnpm-lock.yaml
Labels: ⚙️ Setting

#254 성적 입력 자동저장 오류 개선
  apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
  apps/user/src/app/form/성적입력/성적입력.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.hooks.ts
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/hooks/state/useFormStepState.ts
  apps/user/src/hooks/useUser.tsx
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/form/mutations.ts
Labels: 🔨 Refactor

#251 어드민 페이지에 사이드바 컴포넌트를 제작했습니다
  .vscode/settings.json
  apps/admin/.storybook/main.ts
  apps/admin/package.json
  apps/admin/public/next.svg
  apps/admin/public/svg/logo.svg
  apps/admin/public/vercel.svg
  apps/admin/src/components/common/SideBar/SideBar.stories.ts
  apps/admin/src/components/common/SideBar/SideBar.tsx
  apps/admin/src/constants/common/constants.ts
  apps/user/src/components/common/Header/Header.tsx
  pnpm-lock.yaml
  turbo.json
Labels: ✨ Feature

#257 새로운 전형 선택 디자인 퍼블리싱
  apps/user/src/app/form/전형선택/전형선택.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.state.ts
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#247 인증 전송 제한 로직 구현
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/services/auth/mutations.ts
  packages/maru-ui/src/Input/ButtonInput.tsx
Labels: ✨ Feature

#256 원서접수 제출 단계에 따른 페이지 보여주기
  apps/admin/tsconfig.json
  apps/user/src/app/form/page.tsx
  apps/user/src/app/form/성적입력/성적입력.hooks.ts
  apps/user/src/app/form/자기소개서/자기소개서.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
  apps/user/src/app/page.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/GradePreview/GradePreview.hooks.ts
  apps/user/src/constants/common/constant.ts
  apps/user/src/hooks/useUser.tsx
  apps/user/src/services/form/api.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/services/form/queries.ts
  apps/user/src/types/form/client.ts
  apps/user/src/types/form/remote.ts
  packages/maru-ui/src/CheckBox/CheckBox.tsx
  packages/maru-ui/src/Input/NumberInput.tsx
  packages/maru-ui/src/Radio/Radio.tsx
  packages/maru-ui/src/RadioGroup/RadioGroup.tsx
Labels: ✨ Feature

#265 합격자 발표 페이지 퍼블리싱
  apps/user/src/app/results/final/page.tsx
  apps/user/src/app/results/first/page.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/main/Dday/Dday.hooks.ts
  apps/user/src/components/results/FinalResultsTable/FinalResultsTable.tsx
  apps/user/src/components/results/FirstResultsTable/FirstResultsTable.tsx
  apps/user/src/components/results/ResultsMain/ResultsMain.tsx
  apps/user/src/components/results/ResultsTableFooter/ResultsTableFooter.tsx
  apps/user/src/components/results/ResultsTableHeader/ResultsTableHeader.tsx
  apps/user/src/components/results/ResultsTableItem/ResultsTableItem.tsx
  apps/user/src/components/results/index.ts
  apps/user/src/types/results/client.ts
  packages/maru-hooks/src/useInterval.ts
  packages/maru-ui/index.ts
  packages/maru-ui/src/Button/Button.style.ts
  packages/maru-ui/src/Button/Button.tsx
  packages/maru-ui/src/Button/Button.type.ts
  packages/maru-ui/src/Text/Text.tsx
Labels: ✨ Feature

#264 어드민 공지사항 페이지를 퍼블리싱했습니다.
  apps/admin/.babelrc
  apps/admin/.eslintrc.js
  apps/admin/.eslintrc.json
  apps/admin/next.config.js
  apps/admin/package.json
  apps/admin/src/app/favicon.ico
  apps/admin/src/app/globals.css
  apps/admin/src/app/layout.tsx
  apps/admin/src/app/notice/page.tsx
  apps/admin/src/app/page.module.css
  apps/admin/src/app/page.tsx
  apps/admin/src/components/Provider.tsx
  apps/admin/src/components/common/ListHeader/ListHeader.stories.tsx
  apps/admin/src/components/common/ListHeader/ListHeader.tsx
  apps/admin/src/components/common/ListItem/ListItem.stories.tsx
  apps/admin/src/components/common/ListItem/ListItem.tsx
  apps/admin/src/components/common/SideBar/SideBar.tsx
  apps/admin/src/components/notice/NoticeList/NoticeList.tsx
  apps/admin/src/layouts/AppLayout.tsx
  packages/maru-ui/src/Button/Button.tsx
  packages/maru-ui/src/Text/Text.tsx
  packages/maru-utils/functions/formatCreatedAt.ts
  packages/maru-utils/functions/formatPostedAt.ts
  packages/maru-utils/index.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#267 원서접수 출결상황 버그 수정
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
  apps/user/src/components/form/FinalFormConfirm/FinalFormConfirm.tsx
  apps/user/src/hooks/useUser.tsx
  apps/user/src/types/form/client.ts
Labels: 🐞 Bug

#270 출신학교 및 학력 페이지 입력란 수정했습니다
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
Labels: ✨ Feature

#263 유저 원서접수 초안 제대로 입력이 제대로 되지 않은 경우 경고가 뜨게 했습니다
  apps/user/src/app/favicon.ico
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/지원자정보/지원자정보.tsx
  apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
  apps/user/src/hooks/useUser.tsx
  apps/user/src/store/form/load.ts
  apps/user/src/store/index.ts
  packages/maru-ui/src/Input/ButtonInput.tsx
  packages/maru-ui/src/Input/Input.tsx
  packages/maru-ui/src/Input/Input.type.ts
  packages/maru-ui/src/Input/NumberInput.tsx
  packages/maru-ui/src/Input/PreviewInput.tsx
  packages/maru-ui/src/Input/TimeLimitInput.tsx
Labels: ✨ Feature

#272 flex 유틸리티를 적용하면 깔끔해지는 플렉스 박스에 flex 유틸리티 적용했습니다.
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
  apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
  apps/user/src/components/form/ProgressBar/ProgressBar.tsx
  apps/user/src/components/main/Faq/MainFaqList/MainFaqItem/MainFaqItem.tsx
  packages/maru-ui/src/CheckBox/CheckBox.tsx
  packages/maru-ui/src/Dropdown/Dropdown.tsx
  packages/maru-ui/src/Input/ButtonInput.tsx
  packages/maru-ui/src/Radio/Radio.tsx
Labels: 🔨 Refactor

#274 Text 컴포넌트를 적용할 수 있는 컴포넌트는 Text 컴포넌트 적용
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/form/최종제출/최종제출.tsx
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/faq/FaqList/FaqItem/FaqItem.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/CheckFormComplete/CheckFormComplete.tsx
  apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
  apps/user/src/components/form/GradePreview/GradePreview.tsx
  apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
  apps/user/src/components/main/Dday/Dday.tsx
  apps/user/src/components/main/Faq/MainFaq.tsx
  apps/user/src/components/main/Notice/MainNotice.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
  apps/user/src/components/main/Schedule/ScheduleItem/ScheduleItem.tsx
  apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.tsx
  apps/user/src/components/notice/NoticeList/NoticeItem/NoticeItem.tsx
  apps/user/src/components/results/ResultsTableFooter/ResultsTableFooter.tsx
  apps/user/src/layouts/FormLayout.tsx
  packages/maru-ui/src/Confirm/Confirm.tsx
  packages/maru-ui/src/Dropdown/Dropdown.tsx
  packages/maru-ui/src/Input/TimeLimitInput.tsx
  packages/maru-ui/src/Modal/Modal.tsx
Labels: 🔨 Refactor

#278 useUser 리팩토링
  apps/user/src/app/form/page.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/components/Provider.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/common/Wrappers/AuthWrapper/AuthWrapper.tsx
  apps/user/src/components/common/Wrappers/FormWrapper/FormWrapper.tsx
  apps/user/src/components/common/index.ts
  apps/user/src/components/main/Notice/MainNotice.tsx
  apps/user/src/hooks/useUser.tsx
Labels: 🔨 Refactor

#282 부수러기 코드 없애고 코드 보완하기
  .vscode/settings.json
  apps/admin/.eslintrc.js
  apps/user/.eslintrc.js
  apps/user/src/hooks/useUser.tsx
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/faq/queries.ts
  apps/user/src/services/form/queries.ts
  apps/user/src/services/notice/queries.ts
  apps/user/src/services/user/queries.ts
Labels: ✨ Feature, 🔨 Refactor

#285 최종제출완료 페이지 퍼블리싱 & 초안제출완료 페이지에 애니메이션 추가했습니다.
  apps/user/src/app/form/초안제출완료/초안제출완료.tsx
  apps/user/src/app/form/최종제출완료/최종제출완료.hooks.ts
  apps/user/src/app/form/최종제출완료/최종제출완료.tsx
Labels: ✨ Feature

#291 로그인 페이지에 아이디 글자를 이메일로 변경했습니다.
  apps/user/src/app/login/page.tsx
  apps/user/src/services/auth/mutations.ts
Labels: ✨ Feature

#293 useApiError로 에러 핸들링 & input errorMessage
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/hooks/index.ts
  apps/user/src/hooks/useApiError.ts
  apps/user/src/mocks/handlers/index.ts
  apps/user/src/services/QueryClientProvider.tsx
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/form/mutations.ts
  packages/maru-ui/src/Input/ButtonInput.tsx
  packages/maru-ui/src/Input/ConditionalMessage.tsx
  packages/maru-ui/src/Input/Input.tsx
  packages/maru-ui/src/Input/Input.type.ts
  packages/maru-ui/src/Input/Message.tsx
  packages/maru-ui/src/Input/PreviewInput.tsx
  packages/maru-ui/src/Input/TimeLimitInput.tsx
Labels: ✨ Feature

#295 전형 선택 전형 테이블 수정
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/types/form/client.ts
Labels: ✨ Feature

#301 원서접수 보호자정보 보호자 관계 입력 필드 추가
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
  apps/user/src/constants/form/initial.ts
  apps/user/src/types/form/client.ts
  packages/maru-ui/src/RadioGroup/RadioGroup.tsx
Labels: ✨ Feature

#297 원서접수 subjectList 누락 버그 & accessToken undefined 버그 수정
  apps/user/src/apis/token/refresh.ts
  apps/user/src/app/form/성적입력/성적입력.hooks.ts
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
Labels: 🐞 Bug

#303 Release - user v1.1.0
  apps/user/src/apis/token/refresh.ts
  apps/user/src/app/form/보호자정보/보호자정보.tsx
  apps/user/src/app/form/성적입력/성적입력.hooks.ts
  apps/user/src/app/form/전형선택/전형선택.tsx
  apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
  apps/user/src/constants/form/initial.ts
  apps/user/src/hooks/index.ts
  apps/user/src/hooks/useApiError.ts
  apps/user/src/mocks/handlers/index.ts
  apps/user/src/services/QueryClientProvider.tsx
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/form/mutations.ts
  apps/user/src/types/form/client.ts
  packages/maru-ui/src/Input/ButtonInput.tsx
  packages/maru-ui/src/Input/ConditionalMessage.tsx
  packages/maru-ui/src/Input/Input.tsx
  packages/maru-ui/src/Input/Input.type.ts
  packages/maru-ui/src/Input/Message.tsx
  packages/maru-ui/src/Input/PreviewInput.tsx
  packages/maru-ui/src/Input/TimeLimitInput.tsx
  packages/maru-ui/src/RadioGroup/RadioGroup.tsx
Labels: 🌏 Deploy

#306 원서접수 2분마다 중간저장 로직
  apps/user/src/components/common/Wrappers/FormWrapper/FormWrapper.tsx
Labels: ✨ Feature

#304 헤더에 최대 너비 추가했습니다
  apps/user/src/components/common/Header/Header.tsx
Labels: ✨ Feature

#308 500 페이지 개발
  apps/user/public/svg/error.svg
  apps/user/src/app/error.tsx
  apps/user/src/app/not-found.tsx
  apps/user/src/hooks/useApiError.ts
Labels: ✨ Feature

#312 바뀐 메인 페이지 퍼블리싱
  apps/user/public/svg/school_logo.svg
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
  packages/maru-hooks/index.ts
  packages/maru-hooks/src/useBooleanState.ts
  packages/maru-ui/src/Button/Button.style.ts
  packages/maru-ui/src/Dropdown/Dropdown.tsx
  packages/maru-ui/src/Input/PreviewInput.tsx
Labels: ✨ Feature

#316 구글 애널리틱스 적용
  apps/user/src/app/layout.tsx
  turbo.json
Labels: 🌏 Deploy

#320 review.yml 깃허브 액션 추가
  .github/workflows/review.yml
Labels: ⚙️ Setting

#325 성적 모의 계산 사이트 개발
  apps/user/src/app/error.tsx
  apps/user/src/app/form/성적입력/성적입력.tsx
  apps/user/src/app/grade-simulation/page.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Wrappers/FormWrapper/FormWrapper.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/GradePreview/GradePreview.hooks.ts
  apps/user/src/components/form/GradePreview/GradePreview.tsx
  apps/user/src/constants/common/constant.ts
  apps/user/src/constants/form/data.ts
  apps/user/src/hooks/index.ts
  apps/user/src/hooks/useGradeCaculation.ts
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/FormLayout.tsx
  apps/user/src/store/form/form.ts
  apps/user/src/store/form/subject.ts
  packages/maru-ui/src/Table/Td.tsx
Labels: ✨ Feature

#327 회원가입 전화번호 인증으로 변경
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/store/user/user.ts
  apps/user/src/types/auth/remote.ts
  apps/user/src/types/user/client.ts
Labels: ✨ Feature

#333 원서접수 기간이 아니면 들어가지 못하게하기
  apps/user/src/app/form/성적입력/성적입력.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Wrappers/AuthWrapper/AuthWrapper.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/GradePreview/GradePreview.tsx
  apps/user/src/hooks/useGradeCaculation.ts
Labels: ✨ Feature

#334 모바일 사용성 개선
  apps/user/src/app/mobile/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/middleware.ts
Labels: ✨ Feature

#336 Release - user v1.0.4
  .github/workflows/review.yml
  README.md
  apps/admin/public/svg/logo.svg
  apps/admin/src/app/faq/page.tsx
  apps/admin/src/app/notice/page.tsx
  apps/admin/src/components/faq/FaqTable/FaqTable.tsx
  apps/admin/src/components/faq/FaqTable/FaqTableHeader/FaqTableHeader.tsx
  apps/admin/src/components/faq/FaqTable/FaqTableItem/FaqTableItem.tsx
  apps/admin/src/components/notice/NoticeList/NoticeList.tsx
  apps/user/public/images/school_background.png
  apps/user/public/svg/colabo_logo.svg
  apps/user/public/svg/error.svg
  apps/user/public/svg/logo.svg
  apps/user/public/svg/logo_gray.svg
  apps/user/public/svg/not_found.svg
  apps/user/public/svg/round_bamdoliro.svg
  apps/user/public/svg/round_instagram.svg
  apps/user/public/svg/school_logo.svg
  apps/user/src/app/error.tsx
  apps/user/src/app/form/성적입력/성적입력.tsx
  apps/user/src/app/form/자기소개서/자기소개서.tsx
  apps/user/src/app/grade-simulation/page.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/mobile/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/common/Wrappers/AuthWrapper/AuthWrapper.tsx
  apps/user/src/components/common/Wrappers/FormWrapper/FormWrapper.tsx
  apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/form/GradePreview/GradePreview.hooks.ts
  apps/user/src/components/form/GradePreview/GradePreview.tsx
  apps/user/src/constants/common/constant.ts
  apps/user/src/constants/form/data.ts
  apps/user/src/hooks/index.ts
  apps/user/src/hooks/useGradeCaculation.ts
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/FormLayout.tsx
  apps/user/src/middleware.ts
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/store/form/form.ts
  apps/user/src/store/form/subject.ts
  apps/user/src/store/user/user.ts
  apps/user/src/types/auth/remote.ts
  apps/user/src/types/user/client.ts
  packages/maru-ui/src/Confirm/Confirm.tsx
  packages/maru-ui/src/Table/Td.tsx
  packages/maru-ui/src/Text/Text.tsx
Labels: 🌏 Deploy

#337 자주 묻는 질문 버그 수정
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/components/faq/FaqList/FaqItem/FaqItem.tsx
Labels: 🐞 Bug

#340 원서 접수 성적 입력 페이지에서 과목 추가 시 자동 스크롤하는 기능 없앴습니다
  apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
Labels: ✨ Feature

#343 공지사항 Content 링크 처리
  apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.tsx
  packages/maru-theme/src/global.ts
  packages/maru-utils/functions/convertLink.ts
  packages/maru-utils/index.ts
Labels: ✨ Feature

#341 머리부터발끝까지핫픽스
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/middleware.ts
Labels: 🐞 Bug

#344 바뀐 헤더, 메인페이지 스케줄 디자인 반영하기
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
  apps/user/src/components/main/Schedule/ScheduleItem/ScheduleItem.tsx
Labels: ✨ Feature

#353 머리부터발끝까지핫픽스
  apps/user/src/app/form/초안작성완료/초안작성완료.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
  apps/user/src/components/main/Schedule/Schedule.tsx
  apps/user/src/components/main/Schedule/ScheduleItem/ScheduleItem.tsx
  apps/user/src/middleware.ts
Labels: ✨ Feature

#354 머리부터발끝까지핫픽스
  apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
Labels: ✨ Feature

#358 학교 번호 자동 입력 개발
  apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
  apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
  apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
  apps/user/src/types/form/client.ts
Labels: ✨ Feature

#360 눈에 거슬리는 코드 수정
  apps/user/src/app/error.tsx
  apps/user/src/app/login/login.hooks.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/mobile/page.tsx
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/app/result/final/page.tsx
  apps/user/src/app/result/first/page.tsx
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/main/Faq/MainFaq.tsx
  apps/user/src/components/main/Notice/MainNotice.tsx
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/FormLayout.tsx
  packages/maru-ui/index.ts
  packages/maru-ui/src/Input/Input.tsx
  packages/maru-ui/src/Input/Input.type.ts
  packages/maru-ui/src/Input/NumberInput.tsx
  packages/maru-ui/src/Input/PreviewInput.tsx
  packages/maru-ui/src/Input/SearchInput.tsx
  packages/maru-ui/src/Input/TimeLimitInput.tsx
  packages/maru-ui/src/Link/Link.tsx
  packages/maru-ui/src/Text/Text.tsx
Labels: 🔨 Refactor

#363 인증번호 확인 기능 개발
  apps/user/src/app/score-simulation/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/app/signup/signup.hooks.ts
  apps/user/src/components/common/Header/Header.tsx
  apps/user/src/components/main/SimulatorBox/SimulatorBox.tsx
  apps/user/src/constants/common/constant.ts
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/mutations.ts
  apps/user/src/types/auth/client.ts
  apps/user/src/types/auth/remote.ts
  packages/maru-ui/src/Input/TimeLimitInput.tsx
Labels: ✨ Feature

#349 프로그래스바, 자주 묻는 질문, 공지사항, 푸터 최대 회원가입 페이지 CSS 속성 수정하기
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/form/최종제출/최종제출.tsx
  apps/user/src/app/notice/[id]/page.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/common/Footer/Footer.tsx
  apps/user/src/components/common/Header/Profile/Profile.tsx
  apps/user/src/components/form/ProgressSteps/ProgressSteps.tsx
  apps/user/src/components/form/index.ts
  apps/user/src/layouts/AppLayout.tsx
  apps/user/src/layouts/FormLayout.tsx
Labels: ✨ Feature
