Repository Bamdoliro/marururu, pull requests merged in 2023-06, with the labels that each got.

#69 Feat/#64
  LICENSE
  src/app/form/page.tsx
  src/components/common/Header/index.tsx
  src/layouts/FormLayout.tsx
  src/mocks/handlers.ts
Labels: ✨ Feature

#60 Feat/#59
  src/app/page.tsx
  src/components/main/Notice/index.tsx
  src/components/main/Question/index.tsx
  src/components/main/Schedule/data.ts
  src/components/main/Schedule/index.tsx
  src/components/main/Video/Video.tsx
  src/layouts/MainLayout.tsx
  src/styles/global.css
  yarn.lock
Labels: 🔨 Refactor

#71 Feat/#70
  src/components/common/Button/style.ts
  src/components/common/Button/type.ts
Labels: ✨ Feature

#77 Feat/#74
  src/components/common/Footer/index.tsx
Labels: 🐞 Bug

#81 Feat/#75
  .env.example
  public/assets/ArrowTop.svg
  public/assets/ArrowUnder.svg
  public/assets/B.png
  public/assets/Ig.png
  src/app/faq/page.tsx
  src/app/notice/page.tsx
  src/app/page.tsx
  src/components/common/Flex/Row.tsx
  src/components/common/Header/NavigationBar.tsx
  src/components/common/Header/index.tsx
  src/components/main/FAQ.tsx
  src/components/main/Notice.tsx
  src/components/main/Schedule.tsx
  src/components/main/Video.tsx
  src/components/main/items/NoticeItem.tsx
  src/components/main/items/QuestionItem.tsx
  src/components/main/items/ScheduleItem.tsx
  src/layouts/AppLayout.tsx
  src/layouts/BaseLayout.tsx
  src/layouts/FormLayout.tsx
  src/layouts/MainLayout.tsx
  src/layouts/NoticeLayout.tsx
  src/mocks/dummy.ts
  src/services/main/queries.ts
  src/styles/color.ts
Labels: 🔨 Refactor

#80 Feat/#51
  package.json
  public/assets/SchoolBackground.png
  src/app/page.tsx
  src/components/common/Flex/type.ts
  src/components/main/SchoolRecruitCard.tsx
  src/models/submitTime.ts
  src/utils/functions/timer.ts
  yarn.lock
Labels: ✨ Feature

#92 Feat/#90
  src/app/faq/page.tsx
  src/app/login/page.tsx
  src/app/notice/[detail]/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Header/index.tsx
  src/components/faq/Categories.tsx
  src/components/main/FAQ.tsx
  src/components/main/Notice.tsx
  src/components/main/SchoolRecruitCard.tsx
  src/components/main/items/NoticeItem.tsx
  src/components/main/items/QuestionItem.tsx
  src/components/notice/NoticeItem.tsx
  src/constants/routes.ts
  src/layouts/AppLayout.tsx
  src/lib/axios/index.ts
  src/lib/token/refresh/index.ts
  src/services/auth/mutation.ts
  src/styles/color.ts
Labels: 🔨 Refactor

#94 Feat/#93
  src/components/main/SchoolRecruitCard.tsx
  src/models/submitTime.ts
  src/utils/functions/dayFormatter.ts
Labels: 🐞 Bug

#103 REFACTOR :: moment.js 대신 day.js 라이브러리로 수정했습니다
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  apps/user/package.json
  apps/user/src/components/main/SchoolRecruitCard.tsx
  apps/user/src/models/submitTime.ts
  packages/maru-util/src/useInterval.ts
Labels: 🔨 Refactor

#107 엄청난 개발자의 리뷰 반영 2
  .yarn/cache/@tanstack-eslint-plugin-query-npm-4.29.9-338461f956-d6a3697498.zip
  .yarn/install-state.gz
  apps/user/.eslintrc.js
  apps/user/src/apis/instance/index.ts
  apps/user/src/apis/storage/index.ts
  apps/user/src/apis/token/index.ts
  apps/user/src/apis/token/refresh/index.ts
  apps/user/src/app/faq/page.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/app/notice/page.tsx
  apps/user/src/components/common/Header/index.tsx
  apps/user/src/components/common/Provider/index.tsx
  apps/user/src/components/faq/Categories.tsx
  apps/user/src/components/main/Faq.tsx
  apps/user/src/components/main/Notice.tsx
  apps/user/src/services/QueryClientProvider.tsx
  apps/user/src/services/auth/api.ts
  apps/user/src/services/auth/hooks/useJoin.tsx
  apps/user/src/services/auth/hooks/useLogin.tsx
  apps/user/src/services/auth/mutations.ts
  apps/user/src/services/faq/queries.ts
  apps/user/src/services/main/queries.ts
  apps/user/src/services/notice/queries.ts
  configs/eslint/common.js
  configs/eslint/package.json
  configs/eslint/query.js
  yarn.lock
Labels: 🔨 Refactor

#109 hook으로 비즈니스 로직 분리
  apps/user/src/app/login/hook.ts
  apps/user/src/app/login/page.tsx
  apps/user/src/app/page.tsx
  apps/user/src/app/signup/hook.ts
  apps/user/src/app/signup/page.tsx
  apps/user/src/components/main/Dday.tsx
  apps/user/src/components/main/SchoolRecruitCard.tsx
  apps/user/src/components/main/hooks/Dday.hook.ts
  apps/user/src/components/signup/Terms.tsx
  apps/user/src/components/signup/hooks/Terms.hook.ts
  packages/maru-ui/index.ts
Labels: 🔨 Refactor
